import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import Layout from '@/components/layout/layout'
import Providers from '@/components/providers'
import Manti from '@/components/layout/manti'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Manti>{children}</Manti>
                </Providers>
            </body>
        </html>
    )
}